apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  mongodb-root-username: YWRtaW4=
  mongodb-root-password: cGFzc3dvcmQ=
  # Example:
  # password: {{ .Values.password | b64enc }}